# Generated by Django 3.2.23 on 2024-06-12 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0006_auto_20240528_1411'),
        ('example_robot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplerobot',
            name='is_hook_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examplerobot',
            name='send_result_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examplerobot',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bitrix24.bitrixusertoken'),
        ),
        migrations.AlterField(
            model_name='examplerobot',
            name='dt_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
