# Generated by Django 5.2.6 on 2025-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_robot', '0002_auto_20240612_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplerobot',
            name='started',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
