# Generated by Django 5.2.6 on 2025-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_robot', '0003_alter_examplerobot_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplerobot',
            name='is_success',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
