REST_API_VERSION_LEGACY = 'legacy'
REST_API_VERSION_3 = '3'
REST_API_VERSION_OPTIONS = (
    (REST_API_VERSION_LEGACY, 'Старая версия REST'),
    (REST_API_VERSION_3, 'REST 3.0'),
)

REST_V3_DEFAULT_PAGE_SIZE = 50
REST_V3_MAX_LIST_PAGES = 1000
