# Generated by Django 5.2.6 on 2025-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False, verbose_name='ключ')),
                ('value', models.TextField(verbose_name='значение')),
                ('json_value', models.JSONField(blank=True, null=True, verbose_name='json значение')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
        ),
    ]
