# Generated by Django 5.2.6 on 2025-10-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iu_key_value', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyvalue',
            name='value',
        ),
    ]
