# Generated by Django 3.1.5 on 2021-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False, verbose_name='ключ')),
                ('value', models.TextField(verbose_name='значение')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
            ],
        ),
    ]
