# Generated by Django 5.2.6 on 2025-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvalue',
            name='json_value',
            field=models.JSONField(blank=True, null=True, verbose_name='json значение'),
        ),
    ]
