# Generated by Django 2.2.10 on 2020-07-31 15:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='', max_length=127)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
