# Generated by Django 3.0.7 on 2020-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='bitrix_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
