# Generated by Django 4.2.30 on 2026-05-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0006_auto_20240528_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixusertoken',
            name='refresh_error',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет ошибки'), (1, 'Неверный client_id/secret приложения (WRONG_CLIENT)'), (2, 'Просроченный токен при обновлении (EXPIRED_TOKEN)'), (3, 'Неверный токен при обновлении (INVALID_GRANT)'), (4, 'Приложение не установлено (NOT_INSTALLED)'), (5, 'Не оплачена подписка (PAYMENT_REQUIRED)'), (6, 'Домен отключён или не существует (DOMAIN_ERROR)'), (8, 'Ошибка сервера авторизации (OAUTH_GTE_500)'), (9, 'Неизвестная ошибка (UNKNOWN_ERROR)'), (10, 'Публичная часть сайта закрыта (PORTAL_DELETED)'), (11, 'Портал без service_client_id/secret (NO_CLIENT_CREDENTIALS)'), (12, 'Приложение не установлено (APPLICATION_NOT_INSTALLED)'), (13, 'Доступ запрещён (ERROR_403_or_404)'), (14, 'Неверная авторизация (NO_AUTH_FOUND)'), (15, 'Ошибка авторизации (AUTHORIZATION_ERROR)'), (16, 'Нет доступа (ACCESS_DENIED)'), (17, 'Не найдено приложение (APPLICATION_NOT_FOUND)'), (19, 'Пользователь не имеет доступа к приложению (USER_ACCESS_ERROR)'), (20, 'Бесплатный тариф (FREE_PLAN_ERROR)'), (21, 'Пользователь уволен или заблокирован (UNABLE_TO_AUTHORIZE_USER)'), (22, 'Пользователь удалён или не подтверждён (USER_CANT_BE_AUTHORIZED_IN_CONTEXT)')], default=0),
        ),
    ]
