# Generated by Django 4.1.7 on 2026-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0007_alter_bitrixusertoken_refresh_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixusertoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
