# Generated by Django 4.1.7 on 2026-06-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0008_bitrixusertoken_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitrixusertoken',
            old_name='expires_at',
            new_name='expires',
        ),
    ]
